"""Increase magicspell_hash length

Revision ID: 0a36faee2f7c
Revises: 51f3436ef45b
Create Date: 2025-02-24 14:49:06.550796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a36faee2f7c'
down_revision = '51f3436ef45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.alter_column('magicspell_hash',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.alter_column('magicspell_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
