"""Initial migration

Revision ID: 51f3436ef45b
Revises: 
Create Date: 2025-02-24 00:48:27.062807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f3436ef45b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familyname', sa.String(length=150), nullable=False),
    sa.Column('magicspell_hash', sa.String(length=150), nullable=False),
    sa.Column('member_1', sa.String(length=150), nullable=True),
    sa.Column('member_2', sa.String(length=150), nullable=True),
    sa.Column('member_3', sa.String(length=150), nullable=True),
    sa.Column('member_4', sa.String(length=150), nullable=True),
    sa.Column('member_5', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('familyname')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('poster', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('family')
    # ### end Alembic commands ###
